version: '3.3'
services:
  jenkins-server: 
  image: jenkins/jenkins:lts
  ports:
    - 8080:8080 
    - 50000:50000  # master and worker nodes
  volumes:
    - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
    driver: local



  
